### ISSUE TITLE
DS1042c LA

### ISSUE THREAD

**Issue by Diemon1** [mabl/pyRigolWFM#7]
Hi!
I can`t convert wfm to ols or csv. Rigol DS1042C
wfm file:  http://www2.zippyshare.com/v/34879194/file.html

C:>C:\pyRigolWFM-master\wfmutil.py ols C:\NewFile2.wfm
Traceback (most recent call last):
  File "C:\pyRigolWFM-master\wfmutil.py", line 47, in <module>
    scopeData = wfm.parseRigolWFM(f, args.forgiving)
  File "C:\pyRigolWFM-master\wfm.py", line 311, in parseRigolWFM
    scopeData["triggers"] = parseTriggerHdr(fileHdr["trigHdr1"])
  File "C:\pyRigolWFM-master\wfm.py", line 281, in parseTriggerHdr
    trgDict["source"] = ("CH1", "CH2", "EXT", "AC Line")[trigHdr["source"]]
IndexError: tuple index out of range

**Comment by mabl** [comment]
Hi Diemon,

It looks like we are still missing the trigger configuration parsing for LA. Would you be willing to try out all combinations of LA trigger and post the files here, including the options for these files?

**Comment by Diemon1** [comment]
If i understood correct you also need "Setups" file, that i can save on USB?
Here is the archive with waveform and setups file:
http://www20.zippyshare.com/v/68654790/file.html

channels D15-D8: Turn Off
channels D7-D0: manually turn on D0,D1,D2,D3,D4.  D5,D6,D7 - turn off.
Threshold: User.
